[build]
  command = "npm run build"
  publish = "dist/"

[[edge_functions]]
  path = "/"
  function = "geolocation"

  # Si necesitas usar Node.js en funciones serverless, puedes agregar algo como:
  platform = "node"
